[package]
name = "game_snake"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bevy = {version="0.17.1"}
bevy_text_edit = "0.7.0"
#bevy_simple_text_input = "0.12.0"
#bevy_ui = "0.17.1"
#bevy_ui_text_input = "0.5.2"
getset = "0.1.6"
